version: '3.8'

services:
  # Next.js Application
  cinema-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_NAME=cinema_db
    depends_on:
      - mysql
    networks:
      - cinema-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./index/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinema-network
    restart: unless-stopped

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: yourpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - cinema-network

volumes:
  mysql_data:

networks:
  cinema-network:
    driver: bridge