version: '3.8'

services:
  # Development Next.js with hot reload
  cinema-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_NAME=cinema_db
    depends_on:
      - mysql
    networks:
      - cinema-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./index/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinema-network

volumes:
  mysql_data:

networks:
  cinema-network:
    driver: bridge